// Data backing the Executive Intelligence copilot answers.

export const monthlyBriefing = {
  title: "Monthly NOC Intelligence Summary — May 2026",
  generatedBy: "Generated by Scorpius Executive Intelligence (Copilot Agent)",
  volume: {
    total: 147,
    critical: 39,
    warning: 68,
    low: 40,
  },
  resolution: {
    autoResolved: 82,
    autoResolvedPct: 55.8,
    mttrReductionPct: 63,
  },
  topRootCauses: [
    { cause: "Power failures", count: 34 },
    { cause: "Fiber cuts", count: 28 },
    { cause: "Configuration drift", count: 19 },
    { cause: "Backhaul degradation", count: 16 },
    { cause: "Security events", count: 8 },
  ],
  recommendations: [
    {
      text: "Replace 12 aging battery controllers",
      detail: "Sites: SA-1024, RUH-N-089, and 10 others",
    },
    {
      text: "Upgrade 3 overloaded backhaul links",
      detail: "DXB-T-307, JED-N-112, DAM-H-204",
    },
    {
      text: "Schedule config audit for 7 sites showing drift patterns",
      detail: "Recurring neighbour-list drift after parameter pushes",
    },
  ],
};

export const causeBreakdown = [
  { cause: "Power failures", count: 34, color: "#4f46e5" },
  { cause: "Fiber cuts", count: 28, color: "#0ea5e9" },
  { cause: "Configuration drift", count: 19, color: "#10b981" },
  { cause: "Backhaul degradation", count: 16, color: "#f59e0b" },
  { cause: "Hardware failures", count: 12, color: "#8b5cf6" },
  { cause: "Security events", count: 8, color: "#ef4444" },
];

export const predictiveRisk = [
  { siteId: "SA-1024", region: "Riyadh", riskScore: 94, factor: "Battery controller end-of-life", action: "Replace battery controller", confidence: 91 },
  { siteId: "DXB-T-307", region: "Dubai", riskScore: 82, factor: "Backhaul utilisation > 85%", action: "Upgrade backhaul link", confidence: 86 },
  { siteId: "DAM-K-160", region: "Dammam", riskScore: 76, factor: "Battery cycle count high", action: "Schedule battery test", confidence: 84 },
  { siteId: "JED-E-129", region: "Jeddah", riskScore: 71, factor: "Recurring config drift", action: "Lock golden config", confidence: 80 },
  { siteId: "RUH-N-089", region: "Riyadh", riskScore: 68, factor: "Neighbour-list instability", action: "RAN optimisation review", confidence: 79 },
  { siteId: "AUH-M-093", region: "Abu Dhabi", riskScore: 63, factor: "Peak-hour congestion", action: "Capacity expansion", confidence: 82 },
  { siteId: "DXB-A-340", region: "Dubai", riskScore: 59, factor: "Fiber route shares duct w/ prior cut", action: "Reroute / harden fiber", confidence: 77 },
  { siteId: "JED-N-112", region: "Jeddah", riskScore: 54, factor: "RRU VSWR trending up", action: "Pre-emptive RRU inspection", confidence: 75 },
];

export const ddosWeekTimeline = [
  { time: "Mon 02:14", event: "DDoS — 640 Gbps (JED-N-112)", status: "Mitigated in 52s" },
  { time: "Wed 19:40", event: "Anomalous traffic (AUH-C-051)", status: "Resolved" },
  { time: "Thu 11:05", event: "Intrusion attempt (Core GW-2)", status: "Resolved" },
  { time: "Sat 14:39", event: "DDoS — 2.4 Tbps (Core GW-1)", status: "Mitigated in 45s" },
];

export const quickQuestions = [
  "Give me a summary of last month",
  "What caused most incidents?",
  "Which sites are at risk next month?",
  "Show DDoS incidents this week",
];
